<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.3" />
    <PackageReference Include="TUnit" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorDesktop.Application\BlazorDesktop.Application.csproj" />
    <ProjectReference Include="..\BlazorDesktop.DataGeneration\BlazorDesktop.DataGeneration.csproj" />
    <ProjectReference Include="..\BlazorDesktop.Domain\BlazorDesktop.Domain.csproj" />
    <ProjectReference Include="..\BlazorDesktop.Infrastructure\BlazorDesktop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
